### ISSUE TITLE
Not all the binaries are compiled to executables in the Windows version. 

### ISSUE THREAD

**Issue by sariths** [LBNL-ETA/pyradiance#22]
Refer the discussion here: https://github.com/LBNL-ETA/pyradiance/issues/21#issue-1837109253

**Comment by taoning** [comment]
Remember to add tests for all perl tools.

**Comment by sariths** [comment]
@taoning I finally got around testing this on my Windows machine and it is not an issue. I was able to get Radiance to compile after installing Visual Studio (2022 version) with C++ build tools.
