### ISSUE TITLE
Falsecolor?

### ISSUE THREAD

**Issue by sariths** [LBNL-ETA/pyradiance#29]
Hi @taoning, I was [trying to create an workflow](https://gist.github.com/sariths/233fcc7e5c21dd2ac3e45e07e959e8e3) when I ran across the issue of missing falsecolor. Is this intentional? I understand that [here](https://github.com/LBNL-ETA/pyradiance/blob/8faf6bd2b87c786cf3639fe8415e118f3e62cffc/docs/tutorials.md?plain=1#L57-L78) you have shown an example of creating a falsecolor image. 

It does seem like jumping around hoops to recreate a functionality that is almost integral to Radiance. For the past year (or earlier), falsecolor, genBSDF etc. (all perl based) are being compiled as binaries(exe) on my Windows machine. Since you are already distributing genBSDF, isn't it straightforward to distribute falsecolor also?

Btw, I am stating all this because up until one runs into the falsecolor issue, one can work with pyradiance seamlessly without any dependencies.

**Comment by taoning** [comment]
We can certainly add falsecolor.  All we need to do is add a falsecolor function in `px.py`.  Then add falsecolor to the list of binaries in setup.py.  expose falsecolor function in __init__.py
PR welcomed :)
