### ISSUE TITLE
Runtime Error: ra_tiff fails

### ISSUE THREAD

**Issue by koepferl** [LBNL-ETA/pyradiance#32]
**Describe the bug**
pr.ra_tiff(fls_image,'fls.tiff') seems to fail. 

**To Reproduce**
1) Following https://lbnl-eta.github.io/pyradiance/tutorials/
    https://gist.github.com/sariths/b4cc77d9ca255e7743f03ddc2d0d3a0c

2) 

import os
import pyradiance as pr
from datetime import datetime

%# The files used in this script can be downloaded here: https://github.com/sariths/radTutorialFiles

%#Set the current working directory to room
%#os.chdir(r'E:\radTutorialFiles-main\room')

%#Could be any name.
scene=pr.Scene('simpleSim')

scene.add_material('materials.rad')

for scene_srf in ('Ceiling','Floor','Glazing','Ground','InteriorWall'):
    #scene.add_surface('objects/%s.rad'%scene_srf)
    scene.add_surface('%s.rad'%scene_srf)

%# You can add the longitude and latitude of a location to this. Currently, it defaults to Oakland, California.
%# Please see https://floyd.lbl.gov/radiance/man_html/gensky.1.html
sky_def = pr.gensky(dt=datetime(2023, 11, 11, 11), sunny_with_sun=True)

sky_dome = b"""
skyfunc glow skyglow
0
0
4 .99 .99 1.1 0
skyglow source sky
0
0
4 0 0 1 180
skyfunc glow groundGlow
0
0
4 .99 .99 1.1 0
groundGlow source ground
0
0
4 0 0 -1 180
"""

sky_file = pr.write('day.sky',sky_def + sky_dome,)
scene.add_source(sky_file)

%# The numbers were copied from views/south.vf.
view_frm_file=pr.View(vtype='v',position=list(map(float,'2.67625 5.50846 1.42293'.split())),
                      direction=list(map(float,'-0.0231152 -0.999331 0.0283235'.split())),
                      vup=list(map(float,'-0.000364 0.00721 0.999974'.split())),
                      horiz=79.1044,vert=49.2739)

scene.add_view(view_frm_file)

image=pr.render(scene,ambbounce=3)
image_path='image.hdr'
pr.write(image_path,image)

%# Documentation for falsecolor: https://www.radiance-online.org/learning/documentation/manual-pages/pdfs/falsecolor.pdf/at_download/file
fls_image=pr.falsecolor(image)

%# Documentation for pcond: https://www.radiance-online.org/learning/documentation/manual-pages/pdfs/pcond.pdf/at_download/file
tone_mapped_img=pr.pcond(image_path,human=True)

%# Documentation for ra_tiff: https://www.radiance-online.org/learning/documentation/manual-pages/pdfs/ra_tiff.pdf/at_download/file
fls_tiff=pr.ra_tiff(fls_image,'fls.tiff')
%#tone_mapped_tiff=pr.ra_tiff(tone_mapped_img,'tone_mapped.tiff')

3) Error message

rebuilding octree...
dyld[71435]: Library not loaded: /usr/local/opt/libtiff/lib/libtiff.6.dylib
  Referenced from: <FE82E21B-6655-35FF-ADC9-362B9C605ED7> /Users/greif/opt/anaconda3/lib/python3.9/site-packages/pyradiance/bin/ra_tiff
  Reason: tried: '/usr/local/opt/libtiff/lib/libtiff.6.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/opt/libtiff/lib/libtiff.6.dylib' (no such file), '/usr/local/opt/libtiff/lib/libtiff.6.dylib' (no such file), '/usr/local/lib/libtiff.6.dylib' (no such file), '/usr/lib/libtiff.6.dylib' (no such file, not in dyld cache)
---------------------------------------------------------------------------
CalledProcessError                        Traceback (most recent call last)
~/opt/anaconda3/lib/python3.9/site-packages/pyradiance/anci.py in wrapper(*args, **kwargs)
     21         try:
---> 22             result = func(*args, **kwargs)
     23         except CalledProcessError as e:

~/opt/anaconda3/lib/python3.9/site-packages/pyradiance/px.py in ra_tiff(inp, out, gamma, greyscale, lzw, sgilog, sgilog24, ieee32, primary, exposure, reverse, xyze)
    381     cmd.append(str(out))
--> 382     pout = sp.run(cmd, check=True, input=stdin, stdout=sp.PIPE).stdout
    383     if out is None:

~/opt/anaconda3/lib/python3.9/subprocess.py in run(input, capture_output, timeout, check, *popenargs, **kwargs)
    527         if check and retcode:
--> 528             raise CalledProcessError(retcode, process.args,
    529                                      output=stdout, stderr=stderr)

CalledProcessError: Command '['/Users/greif/opt/anaconda3/lib/python3.9/site-packages/pyradiance/bin/ra_tiff', '-g', '2.2', '-', 'fls.tiff']' died with <Signals.SIGABRT: 6>.

During handling of the above exception, another exception occurred:

RuntimeError                              Traceback (most recent call last)
/var/folders/c2/tthc2_6j741c3rvx9vpjppwh0000gn/T/ipykernel_71378/1612623305.py in <module>
     63 
     64 # Documentation for ra_tiff: https://www.radiance-online.org/learning/documentation/manual-pages/pdfs/ra_tiff.pdf/at_download/file
---> 65 fls_tiff=pr.ra_tiff(fls_image,'fls.tiff')
     66 #tone_mapped_tiff=pr.ra_tiff(tone_mapped_img,'tone_mapped.tiff')

~/opt/anaconda3/lib/python3.9/site-packages/pyradiance/anci.py in wrapper(*args, **kwargs)
     23         except CalledProcessError as e:
     24             errmsg = e.stderr or b""
---> 25             raise RuntimeError(
     26                 f"An error occurred with exit code {e.returncode}: {errmsg.decode()}"
     27             )

RuntimeError: An error occurred with exit code -6: 

**Expected behavior**
tiff output

**Screenshots**

<img width="493" alt="Screenshot 2024-02-19 at 13 03 59" src="https://github.com/LBNL-ETA/pyradiance/assets/2587204/814f7220-a186-4c57-bb7d-2b28593421d3">

<img width="614" alt="Screenshot 2024-02-19 at 13 04 27" src="https://github.com/LBNL-ETA/pyradiance/assets/2587204/dc5c8e75-fb49-4bab-b077-13ca7fcc05d4">

**Desktop (please complete the following information):**
 - OS: MacOS 
 - Ventura

**Comment by taoning** [comment]
It appears that libtiff linking is broken in macOS Radiance.  We will try to fix it the next releases.
As an immediate solution:
1. Install [homebrew](https://brew.sh) in not installed.  (macports also works)
2. run `brew install libtiff`
3. run `sudo mkdir -p /usr/local/opt/libtiff/lib`
4. run `sudo ln /opt/homebrew/lib/libtiff.6.dylib /usr/local/opt/libtiff/lib/libtiff.6.dylib`

**Comment by koepferl** [comment]
@taoning I installed: everything. 

I get this warning

dyld[73559]: Library not loaded: /usr/local/opt/libtiff/lib/libtiff.6.dylib
  Referenced from: <FE82E21B-6655-35FF-ADC9-362B9C605ED7> /Users/greif/opt/anaconda3/lib/python3.9/site-packages/pyradiance/bin/ra_tiff
  Reason: tried: '/usr/local/opt/libtiff/lib/libtiff.6.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/opt/libtiff/lib/libtiff.6.dylib' (no such file), '/usr/local/opt/libtiff/lib/libtiff.6.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/usr/local/lib/libtiff.6.dylib' (no such file), '/usr/lib/libtiff.6.dylib' (no such file, not in dyld cache)


The file is there, but it appears to have ``mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')``

ls /usr/local/opt/libtiff/lib/libtiff.6.dylib 
/usr/local/opt/libtiff/lib/libtiff.6.dylib

**Comment by taoning** [comment]
I should have asked, are you on arm64(M series) Mac or older Intel Mac?

**Comment by koepferl** [comment]
Chip Apple M1 Max from 2021

**Comment by koepferl** [comment]
Hi, I see that you updated this: https://lbnl-eta.github.io/pyradiance/tutorials/

What sky, room and material are you using here?

Thanks.

**Comment by taoning** [comment]
some random model. You can use `gen room` for this tutorial as well.

**Comment by koepferl** [comment]
Wonderful! 

just so you know, this fixes are needed for it to work

norm = matplotlib.colors.LogNorm()

plt.axis("off")
fimage = cmap(norm(luminance))
plt.colorbar(plt.cm.ScalarMappable(norm=norm, cmap=cmap), label=r"$\mathrm{cd/m^2}$")
plt.imshow(luminance)
