### ISSUE TITLE
Support for obj2mesh

### ISSUE THREAD

**Issue by Moult** [LBNL-ETA/pyradiance#33]
Is it possible to add support to the obj2mesh binary? :)

**Comment by taoning** [comment]
absolutely

**Comment by taoning** [comment]
added to v0.4.0

**Comment by chiragsingh1711** [comment]
> added to v0.4.0

Thankyou so much @taoning 
obj2mesh was a function that we really required in our project.

**Comment by Moult** [comment]
Thank you so much as well! Incredible response!
