### ISSUE TITLE
manylinux1 is deprecated when distributing on PyPI

### ISSUE THREAD

**Issue by Moult** [LBNL-ETA/pyradiance#34]
On PyPI, currently the distribution uses the format `manylinux1_...` which according to [PEP 600](https://peps.python.org/pep-0600/) is now deprecated I believe, so the new syntax should be `manylinux_${GLIBCMAJOR}_${GLIBCMINOR}_${ARCH}`, so something akin to `manylinux_2_17_x86_64` should be used (depending on the min glibc of course) :)

**Comment by taoning** [comment]
see v0.4.1
