### ISSUE TITLE
Support for MacOS Intel

### ISSUE THREAD

**Issue by Moult** [LBNL-ETA/pyradiance#35]
This might be a long shot, but currently there is only support for MacOS Silicon. Is there a possibility of supporting MacOS Intel? I ask this because there is currently work to integrate this in the BlenderBIM Add-on (https://blenderbim.org/) which distributes for both MacOS Intel and Silicon.

**Comment by taoning** [comment]
We do support MacOS Intel.  There is something wrong with out CI.

**Comment by taoning** [comment]
see v0.4.1
