### ISSUE TITLE
Error when file path contains spaces

### ISSUE THREAD

**Issue by manuvarkey** [LBNL-ETA/pyradiance#38]
**Describe the bug**
When the file path to `materials.rad` or `scene.rad` contains white spaces, error is raised when calling subprocess for `rad` inside `pyradiance.render(scene)` as follows.

```
/home/eee/.local/lib/python3.11/site-packages/pyradiance/bin/rad: bad variable assignment: render=  (ignored)
/home/eee/Desktop/tetst/pyradiance: No such file or directory
Traceback (most recent call last):
  File "/home/eee/.local/lib/python3.11/site-packages/pyradiance/anci.py", line 22, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/eee/.local/lib/python3.11/site-packages/pyradiance/util.py", line 285, in rad
    return sp.run(cmd, stdout=sp.PIPE, check=True).stdout
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/eee/.local/lib/python3.11/site-packages/pyradiance/bin/rad', '-n', '/dev/null', 'ZONE=I -0.50001 12.5 -1.50001 11.5 -3.44116 9.55886', 'OCTREE=ascene.oct', 'scene=/home/eee/Desktop/tetst/pyradiance test/output/scene.rad', 'materials=/home/eee/Desktop/tetst/pyradiance test/output/materials.rad', 'QUALITY=Medium', 'VARIABILITY=Medium', 'DETAIL=Medium', 'render= ']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/eee/Desktop/tetst/pyradiance test/pyradiance_test.py", line 18, in <module>
    image = pr.render(scene)
            ^^^^^^^^^^^^^^^^
  File "/home/eee/.local/lib/python3.11/site-packages/pyradiance/util.py", line 636, in render
    for l in rad(os.devnull, dryrun=True, varstr=radvars).decode().splitlines()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eee/.local/lib/python3.11/site-packages/pyradiance/anci.py", line 25, in wrapper
    raise RuntimeError(
RuntimeError: An error occurred with exit code 1: 

```

**To Reproduce**

Run `pyradiance_test.py` inside the `pyradiance test` folder (files in attachment) to reproduce the error (Change `/home/eee/Desktop/tetst/pyradiance test/output` to the correct path).

[pyradiance test.zip](https://github.com/user-attachments/files/16331422/pyradiance.test.zip)

`pyradiance_test.py`
```
import os
import pyradiance as pr

output_dir = "/home/eee/Desktop/tetst/pyradiance test/output"

# Py Radiance Rendering code
scene = pr.Scene("ascene")

material_path = os.path.join(output_dir, "materials.rad")
scene_path = os.path.join(output_dir, "scene.rad")

scene.add_material(material_path)
scene.add_surface(scene_path)

aview = pr.View(position=(1, 1.5, 1), direction=(1, 0, 0))
scene.add_view(aview)

image = pr.render(scene)

raw_hdr_path = os.path.join(output_dir, "raw.hdr")
with open(raw_hdr_path, "wb") as wtr:
    wtr.write(image)
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Version 0.4.1

**Comment by manuvarkey** [comment]
Error seems to be due to presence of white-spaces inside paths supplied as arguments to subprocess. Following hack to `util.py` seems to solve the issue.

https://github.com/manuvarkey/pyradiance/pull/1

**Comment by taoning** [comment]
I think you are right.  I'd like to look into this issue.
I am missing a `model.rtm` file referenced in your `scene.rad` file.

**Comment by taoning** [comment]
should be fixed now. give it a try

**Comment by manuvarkey** [comment]
@taoning Seems working now. Thanks for the prompt response.

**Comment by Moult** [comment]
I don't really understand this fix.  e.g. https://github.com/LBNL-ETA/pyradiance/commit/053793818d2a589ef4c3e6379613d1e5fe7474f2 I thought subprocess.run would already properly handle arguments with spaces in them? Why handle it yourself, wouldn't that just break if an apostrophe is used in the filename instead? Won't it also be less secure because you're just passing in in the string directly without any sanitisation?
